In [1]:
import matplotlib.pyplot as plt
import numpy as np
import cv2
import os
import PIL
import tensorflow as tf
import glob
import  sklearn
import pandas as pd

from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
from keras.preprocessing.image import ImageDataGenerator

import np_utils
from keras.utils.np_utils import to_categorical

from tensorflow import keras
from tensorflow.keras import layers

In [2]:
dataset='C:\\Users\\Lenovo\\Desktop\\RESEARCH PROJECT\\Covid19-dataset\\train'

In [5]:
import pathlib
datadir = pathlib.Path(dataset)
datadir

WindowsPath('C:/Users/Lenovo/Desktop/RESEARCH PROJECT/Covid19-dataset/train')

In [25]:
Categories=['Covid','Normal','Viral pneumonia']
flat_data_arr=[]
target_arr=[]

for i in Categories:
    
    print(f'loading... category : {i}')
    path=os.path.join(datadir,i)
    for img in os.listdir(path):
        img_array=cv2.imread(os.path.join(path,img))
        img_resized=cv2.resize(img_array,(180,180))
        flat_data_arr.append(img_resized.flatten())
        
        target_arr.append(Categories.index(i))
    print(f'loaded category:{i} successfully')
flat_data=np.array(flat_data_arr)
target=np.array(target_arr)
df=pd.DataFrame(flat_data) #dataframe
df['Target']=target
x=df.iloc[:,:-1] #input data 
y=df.iloc[:,-1] #output data
for i in Categories:
    target_arr.append(Categories.index(i))

loading... category : Covid
loaded category:Covid successfully
loading... category : Normal
loaded category:Normal successfully
loading... category : Viral pneumonia
loaded category:Viral pneumonia successfully

In [34]:
x = x/255.0

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=10,test_size=.20)

In [36]:
from sklearn.svm import SVC
svc = SVC(kernel='linear',gamma='auto')

In [26]:
X_train.shape

(200, 1)

In [37]:
svc.fit(X_train, y_train)
print('The Model is trained well with the given images')

The Model is trained well with the given images

In [38]:
y2 = svc.predict(X_test)

In [39]:
from sklearn.metrics import accuracy_score
print("Accuracy on unknown data is",accuracy_score(y_test,y2))

Accuracy on unknown data is 0.9215686274509803

In [40]:
from sklearn.metrics import classification_report
print("Accuracy on unknown data is",classification_report(y_test,y2))

Accuracy on unknown data is               precision    recall  f1-score   support

           0       0.95      0.95      0.95        22
           1       0.93      0.87      0.90        15
           2       0.87      0.93      0.90        14

    accuracy                           0.92        51
   macro avg       0.92      0.92      0.92        51
weighted avg       0.92      0.92      0.92        51

In [41]:
result = pd.DataFrame({'original' : y_test,'predicted' : y2})

In [42]:
result

     original  predicted
56          0          0
127         1          1
60          0          0
152         1          1
106         0          0
119         1          1
194         2          2
91          0          0
216         2          2
49          0          0
163         1          0
183         2          2
241         2          2
212         2          2
26          0          0
224         2          1
63          0          0
147         1          2
209         2          2
87          0          0
58          0          0
238         2          2
138         1          1
144         1          1
130         1          1
55          0          0
10          0          0
35          0          0
232         2          2
103         0          0
136         1          1
204         2          2
80          0          0
235         2          2
186         2          2
6           0          2
166         1          1
24          0          0
76          0          0
105         0          0
19          0          0
114         1          1
59          0          0
124         1          1
211         2          2
1           0          0
176         1          1
187         2          2
161         1          1
61          0          0
180         1          1